export const ADD_TODO = "ADD_TODO";
export const ADD_TODO_SUCCESSFUL = "ADD_TODO_SUCCESSFUL";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const TOGGLE_TODO_SUCCESSFUL = "TOGGLE_TODO_SUCCESSFUL";
export const TOGGLE_TODO_FAILURE = "TOGGLE_TODO_FAILURE";
export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE";
export const SET_FILTER = "SET_FILTER";
